### ISSUE TITLE
Scrum Updates for May 30

### ISSUE THREAD

**Issue by KKelvinLo** [nksiu/Spotify-Album-Radar#1]
1. Write down your CSID
2. What you worked on this past iteration
3. What were any major issues/challenges you ran into
4. What do you plan on working for this iteration

**Comment by KKelvinLo** [comment]
1. x1y1b
2. Project requirements 
3. No issues
4. Setup frontend / spotify oauth

**Comment by barrysin** [comment]
1. j3n1b
2. Worked on the project requirements, specifically the prototype sketches.
3. No issues in particular. It was hard to come up with an idea at first, but with the power of friendship, we came up with a BOMB idea.
4. Likely set up react components for the login or main page. Figuring out how to use the spotify api.

**Comment by nksiu** [comment]
1. j4j1b
2. Project Requirements
3. No issues, was a little difficult to figure out how all the parts of the system were going to interact with each other
4. Setup login page and the spotify oauth server (see if it's possible to create within this repo or need to to in a separate one)

**Comment by tlei99** [comment]
1.d4j1b
2. Worked on developing project milestones/requirements
3. No issues
4. Investigate layout of front-end components, mocking front-end UI with react. Also, given enough time, looking into email services that we could use
