### ISSUE TITLE
Scrum Updates for June 27

### ISSUE THREAD

**Issue by tlei99** [nksiu/Spotify-Album-Radar#30]
1. Write down your CSID
2. What you worked on this past iteration
3. What were any major issues/challenges you ran into
4. What do you plan on working for this iteration

**Comment by nksiu** [comment]
1. j4j1b
2. Set up OAuth and helped out creating endpoints
3. cookie was not persisting properly and still need to discuss how to handle user sessions
4. Clean up user session, introduce redux and mongodb

**Comment by KKelvinLo** [comment]
1. x1y1b
2. Setup login and logout feature
3. layouts and styling, need to figure out consistency
4. Clean up user experience with ui, modularize user sessions, storing data with mongodb

**Comment by barrysin** [comment]
1. j3n1b
2. Set up endpoints for new releases page. Link with front end
3. Had trouble figuring out how to link user page data with new releases page
4. Work on fixing and finalizing the features currently available.

**Comment by tlei99** [comment]
1. d4j1b
2. Setup artist query and management feature; Created endpoints to link with spotify
3. Figuring out the proper endpoint options and formatting; Creating a consistent + appealing UI
4. Working on cleaning up user profile page; Linking artist management to DB
