### ISSUE TITLE
Scrum Updates for July 18th

### ISSUE THREAD

**Issue by tlei99** [nksiu/Spotify-Album-Radar#42]
1. Write down your CSID
2. What you worked on this past iteration
3. What were any major issues/challenges you ran into
4. What do you plan on working for this iteration

**Comment by tlei99** [comment]
1. d4j1b
2. Integrating saving/removing artists from the db (per user)
3. Refactoring the front end to save user subscribed artists on db instead of locally; Many areas of code needed to be examined for conflicts
4. Working on caching of weekly releases, investigating modifying user playlists

**Comment by barrysin** [comment]
1. j3n1b
2. Adding/changing the days range for new releases to db, updated front end design on multiple pages
3. Had trouble with the artist list filtering when I had to grab inputs from the form.
4. Investigate how to add email notifications.

**Comment by KKelvinLo** [comment]
1. x1y1b
2. Added the about me endpoint/ setup schemas
3. Figuring out what had to go into schemas
4. Clean up front end and figure out deploying

**Comment by nksiu** [comment]
1. j4j1b
2. Added redux and called the necessary endpoints
3. Had issues with cors and some of the propagation of props so the components were in the right state
4. Further improve the props propagation as it's still a little buggy and help create the playlist parsing
