### ISSUE TITLE
Scrum Updates for Aug 1st

### ISSUE THREAD

**Issue by tlei99** [nksiu/Spotify-Album-Radar#46]
1. Write down your CSID
2. What you worked on this past iteration
3. What were any major issues/challenges you ran into
4. What do you plan on working for this iteration

**Comment by tlei99** [comment]
1. d4j1b
2. Setting up the playlist artist parser, and refactoring subscribed artist list to use global state via redux
3. Synchronizing a user's subscribed artists through artist management via both playlist parsing and individual artists
4. Setting up user-specified playlist release updates, cleaning up and improving user profile management UI

**Comment by nksiu** [comment]
1. j4j1b
2. Created the playlist dropdown and helped with deployment
3. Deployment took some time due to figuring out environment vars and file restructuring 
4. Clean up UI and look into playlist creations based off of following artists

**Comment by barrysin** [comment]
1. j3n1b
2. Set up new releases database collection for weekly cron job. Created temporary endpoints to pull newest releases from spotify
3. Had trouble with asynchronous calls and promises. There were a lot of calls that took some time, had trouble making it all work together
4. Look up how to set up email notifications

**Comment by KKelvinLo** [comment]
1. X1y1b
2. Deployed app to heroku, restructured files and configured endpoints
3. Had trouble Figuring out proper Endpoints for deployment
4. Improving user ui and cleaning up backend
