### ISSUE TITLE
Scrum Updates for June 13

### ISSUE THREAD

**Issue by KKelvinLo** [nksiu/Spotify-Album-Radar#6]
1. Write down your CSID
2. What you worked on this past iteration
3. What were any major issues/challenges you ran into
4. What do you plan on working for this iteration

**Comment by KKelvinLo** [comment]
1. x1y1b
2. Designed the Navbar with styled-components and used router to link the pages
3. our project is backend heavy, so as a team we had to decide which components we can get done for the frontend without wasting a lot of resources on mocks 
4. setting up the backend, enabling Spotify auth api

**Comment by tlei99** [comment]
1. d4j1b
2. Designed the User Management page to support adding/removing tracked artists, along with searches of tracked artists.
3. Finding the best way to represent the list of artists, as the list of artists can range from few (5-10) entries to hundreds of entries. Also, finding a functional and appealing design + layout for the page occupied most of my time.
4. Creating the server endpoints, and looking into how our backend data is stored, along with further refining the front-end styling + features for the user management page.

**Comment by nksiu** [comment]
1. j4j1b
2. Designed the New Releases page and used mock data to show progress. Also did the initial boiler plate of structuring the files. Looked into options of handling oauth for spotify and came to the conclusion of setting up our own server to handle it.
3. Thought about how to create our components without the backend complete as there's no data for the components to take in. Also will most likely need to implement lazy loading for when there are a lot of new releases
4. Making the frontend more responsive but mainly setting up the backend to start consuming the spotify apis.

**Comment by barrysin** [comment]
1. j3n1b
2. Created form for adding new artists to the user management page. Add delete functionality for the list of artists.
3. Had a hard time matching up all the elements with CSS. It was challenging to figure out what components we would need to implement as a team.
4. Linking backend to front end components, fixing up front end mocks, work on setting up spotify api
